import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Next Experimental",
  description: "Generated by create next app",
};

const googleSansFlex = localFont({
  src: "./fonts/GoogleSansFlex.ttf",
  variable: "--font-google-sans-flex",
  display: "swap",
  weight: "100 200 300 400 500 600 700 800 900",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${googleSansFlex.variable} antialiased`}>
        <h1 className="text-red-500">Navbar EXPERIMENTAL</h1>
        {children}
        <h1 className="text-red-500">Footer EXPERIMENTAL</h1>
      </body>
    </html>
  );
}
